name: HERO DEX
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^1.2.1
  percent_indicator: ^4.2.3
  provider: ^6.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/launcher_icon.png"
  android: true
  image_path_android: "assets/launcher_icon_android.png"
  adaptive_icon_foreground: "assets/launcher_icon_android_foreground.png"
  adaptive_icon_background: "assets/launcher_icon_android_background.png"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true

flutter:
  uses-material-design: true
